LICENSE, package.json
Reverts dev-protocol/clubsx#54
=> Revert "Use PolyForm Perimeter License 1.0.0"

package.json, src/components/list/cards.tsx, src/constants/products.ts, src/pages/sites_/[site]/buy/index.astro, src/pages/sites_/[site]/fiat/index.astro, src/pages/sites_/[site]/nft/index.astro, yarn.lock
- Adds Buy with Fiat page
- Updates Cards component to handle USD or ETH
TODO: The link when clicking on a USD card needs to be set.
=> adds initial fiat layout

scripts/populate.mjs, src/plugins/admin/index.ts
- Adds metadata to populate script
- Updates general admin path like '/admin'
=> adds meta to populate script; updates general admin path

scripts/populate.mjs
=> removes meta from populate

src/pages/sites_/[site]/admin/[...page].astro, src/pages/sites_/[site]/admin/updateConfig.ts, src/plugins/admin/index.astro
Creates an endpoint that updates the config
=> Admin on submit config

src/components/Join/JoinCheckout.vue, src/components/Wallet/ConnectButton.vue, src/constants/connection.ts, src/layouts/Default.astro
Instead of using dev-elements directly, use the high-level API exported by clubs-core.
=> Use the latest Core API

scripts/populate.mjs, src/pages/sites_/[site]/admin/[...page].astro, src/plugins/membership/admin.astro, src/plugins/membership/index.ts
=> Empty membership plugin

src/pages/sites_/[site]/[...page].astro
Fixes missing title and members count
=> fixes missing title and members count

src/pages/sites_/[site]/admin/[...page].astro, src/plugins/quests/admin.astro, src/plugins/quests/components/AdminQuestsForm.vue, src/plugins/quests/index.ts
Add admin page for the Quests plugin
=> ft: quests admin

package.json, yarn.lock
=> updates core

src/components/Join/JoinClub.vue, src/plugins/home/index.astro, src/plugins/join/index.astro
Replaces placeholder in JoinClub.vue with dynamic value
=> replace placeholder with dynamic value

astro.config.mjs, package.json, src/components/Badges/Badges.astro, src/components/Join/JoinClub.vue, src/components/Primitives/Hashi/HSButton.vue, src/components/Quests/Quests.astro, src/components/Sidebar/Sidebar.vue, src/components/list/cards.jsx, src/components/list/cards.tsx, yarn.lock
Add prefetch hook to load pages concurrently and provide for better UX. This is achieved by adding the prefetch plugin in astro config and adding a rel prefetch to all the routes/links.
=> feat: add astro prefetch

scripts/populate.mjs, src/components/Primitives/CLBTier.vue, src/plugins/message/forms.json, src/plugins/message/index.astro, src/plugins/message/index.ts, src/plugins/message/types.ts
Add index page that shows information about the NFT gated contact form. Update the message plugin options to use name, description, membership required and other meta info.
=> feat: add index of nft gated contact form

src/plugins/message/index.ts
Added in the missing props required by the contact form for the NFT gated contact form plugin.
=> fix: add missing props in the NFT gated contact form component

package.json, src/pages/sites_/[site]/message/sendMessage.ts, src/plugins/message/[id].astro, src/plugins/message/components/MessageForm.vue, yarn.lock
Added in server side validation for the NFT gated contact form. Upon submission, the data is encoded hashed and a message is signed. The signed message along with the data is passed to server side. The server side then validated the authenticity of the signed message.
=> feat: server side validation for nft gated contact form.

src/fixtures/utility.ts, src/plugins/message/[id].astro, src/plugins/message/components/MessageForm.vue, src/plugins/message/types.ts
Add NFT gateway contact form client validation. The validation checks whether the user has the required set of validations or not.
=> feat: add nft gateway client validation

scripts/populate.mjs, src/components/Join/JoinCheckout.vue, src/components/list/cards.tsx, src/constants/products.ts, src/plugins/buy/[id].astro, src/plugins/buy/index.astro, src/plugins/buy/index.ts
Adds gateway fee and payload to JoinCheckout for Kogenji.
Updates Product type
=> products updated with gateway fees for kogenji

package.json, yarn.lock
=> updates clubs-core

scripts/populate.mjs, src/components/Global/Navbar.vue, src/constants/navLink.ts, src/layouts/Default.astro
Adds dynamic nav links to header
https://freedcamp.com/view/3250562/tasks/panel/task/48914043
=> adds dynamic navLinks to header

scripts/populate.mjs
=> feat: add memberhsips in kogenji

src/layouts/Landing.astro, src/pages/index.astro
Adds initial landing page with "start your club" button.
Adds Landing layout.
https://freedcamp.com/view/3250562/tasks/panel/task/49434237
=> Landing start club

scripts/populate.mjs, src/components/Global/Navbar.vue, src/layouts/Default.astro
=> implement the header links

scripts/populate.mjs, src/components/Global/Navbar.vue, src/components/list/cards.tsx, src/layouts/Default.astro
Move the links like stakes.social and youtube to clubsconfig and populate the db. Also, add in the description to be shown in the nft cards if the description is present.
=> feat: make navigation more dynamic and update nft cards.

src/components/GetStarted/GetStarted.vue
Adds listener to popup window. Navigates to next page with network and address query params after tokenized.
=> listener for popup message

src/components/WelcomeWizard/WelcomeWizard.svelte, src/components/WelcomeWizard/WelcomeWizardStep.svelte, src/pages/setup/homepage.astro, src/pages/setup/memberships.astro, src/pages/setup/plugins.astro
Adds basic wizard stepper. Still needs better design.
=> basic wizard stepper

package.json, scripts/populate.mjs, yarn.lock
Updates clubs-core and adds chainId and rpcUrl to config
=> adds chainId and rpcUrl to config

scripts/populate.mjs, src/components/Hero/hero.jsx, src/components/Hero/hero2.jsx, src/plugins/nft/index.astro, src/plugins/nft/index.ts
Replace various static values for the hero section with dynamic values coming from clubs configuration.
Notes: To put in default values for these title, description and other params to act as placeholder in case of unwanted event.
=> fix: replace nft plugin static values with dynamic values

scripts/populate.mjs, src/components/Hero/hero.jsx, src/components/Hero/hero2.jsx, src/components/Join/JoinCheckout.vue, src/components/list/cards.tsx, src/plugins/fiat/index.astro, src/plugins/fiat/index.ts, src/plugins/nft/index.astro, src/plugins/nft/index.ts
Add some improvements for Kogenji
=> update for kogenji

src/components/Join/JoinCheckout.vue, src/components/Join/JoinClub.vue, src/plugins/buy/[id].astro, src/plugins/buy/index.ts, src/plugins/home/index.astro, src/plugins/home/index.ts, src/plugins/join/[id].astro, src/plugins/join/index.astro, src/plugins/join/index.ts
Support `rpcUrl` in under @components/Join
=> Support `rpcUrl` in under @components/Join

src/components/AdminMembershipsForm/AdminMembershipsForm.svelte, src/pages/sites_/[site]/setup/memberships.astro, src/plugins/membership/admin.astro
Initializes membership setup.
We still need the actual membership form completed for this.
=> initializes membership setup

src/plugins/message/[id].astro, src/plugins/message/index.astro, src/plugins/message/index.ts
=> some tweak for message component

scripts/populate.mjs
=> Use 1/100 pricies for testnet

src/components/AdminHomeForm/AdminHomeForm.svelte
Add option to add images to What We Do and Perks section in the admin section for home.
=> feat: add adding image option in home admin.

src/components/Domain/Domain.vue, src/pages/almost-there.astro, src/pages/domain.astro
=> changes "almost there" to domain mocks

scripts/populate.mjs, src/layouts/Default.astro
=> Edit the configuration for kogenji

src/components/Join/JoinCheckout.vue, src/components/Sidebar/Sidebar.vue
=> Remove APY related sections

src/components/AdminHomeForm/AdminHomeForm.svelte, src/components/ProfileSetupForm/ProfileSetupForm.svelte, src/components/WelcomeWizard/WelcomeWizard.svelte, src/fixtures/imgur/index.ts, src/layouts/Setup.astro, src/pages/sites_/[site]/setup/homepage.astro, src/pages/sites_/[site]/setup/profile.astro, src/plugins/home/admin.astro
Related to https://freedcamp.com/view/3250562/tasks/panel/task/49845483.
Creates a Profile page section in the Welcome Wizard
=> initial profile wizard ui setup

src/pages/api/verifySiteName/[...site].ts
To check the wanted site name is available, we can use this `verifySiteName` API.
For example:
```ts
const site = 'valid-name'
const res = await fetch(`/api/verifySiteName/${site}`)
const success = res.ok
const result = await res.json()
console.log({ success, result }) // {success: true, result: {}}
```
```ts
const site = 'invalid-name'
const res = await fetch(`/api/verifySiteName/${site}`)
const success = res.ok
const result = await res.json()
console.log({ success, result }) // {success: false, result: {error: "ERROR MESSASE"}}
```
=> `verifySiteName` API

package.json, src/fixtures/firebase/index.ts, src/pages/api/updateDraftConfig.ts, yarn.lock
Remove the commented firebase auth from updateDraftConfig.
Notes (**optional**): We need to confirm that the firebase-admin app is initialized with proper arguments in the code.
=> feat: remove firebase auth comments

package.json, src/plugins/admin/index.ts, src/plugins/buy/index.ts, src/plugins/community/index.ts, src/plugins/fiat/index.ts, src/plugins/home/index.ts, src/plugins/join/index.ts, src/plugins/me/index.ts, src/plugins/members/index.ts, src/plugins/membership/index.ts, src/plugins/message/index.ts, src/plugins/nft/index.ts, src/plugins/perks/index.ts, src/plugins/quests/index.ts, yarn.lock
=> Install @devprotocol/clubs-core@0.10.1 and set category all plugins

src/components/AdminHomeForm/AdminHomeForm.svelte, src/components/SetupDesign/SetupDesign.svelte, src/constants/homeConfig.ts, src/pages/sites_/[site]/setup/design.astro, src/pages/sites_/[site]/setup/homepage.astro
Adds "Design" page for setup related to https://freedcamp.com/view/3250562/tasks/panel/task/49845930
=> Setup Design Page

src/pages/index.astro
changes "getting started" link to domain
=> changes link to domain

package.json, src/components/Global/Skeleton.svelte, src/components/SetupDesign/SetupDesign.svelte, src/components/WelcomeWizard/WelcomeWizard.svelte, src/fixtures/imgur/index.ts, src/layouts/Setup.astro, src/pages/sites_/[site]/setup/design.astro, yarn.lock
=> [Clubs] Design patch: /setup/design

src/components/WelcomeConnect/WelcomeConnect.svelte, src/layouts/Landing.astro, src/layouts/Setup.astro, src/pages/authentication/[siteName].astro, src/pages/connect/[siteName].astro
=> [Clubs] Design patch: /connect and /authenticating

astro.config.mjs, src/components/ProfileSetupForm/ProfileSetupForm.svelte, src/components/WelcomeWizard/WelcomeWizard.svelte, src/components/WelcomeWizard/WelcomeWizardStep.svelte, src/layouts/Setup.astro, src/pages/sites_/[site]/setup/basic.astro
=> [Clubs] Design patch: /setup/basic

astro.config.mjs, package.json, src/constants/homeConfig.ts, src/plugins/home/index.astro, yarn.lock
Replace `whatWeDo`, `perks` and `quote`, and with `body (string)` in the homepage. Modify the plugins/home/index.astro file to do so.
=> feat: use markdown on the homepage.

src/fixtures/dev-kit/index.ts, src/plugins/admin/AdminOverview.svelte, src/plugins/admin/GeneralAdminOverview.svelte, src/plugins/admin/index.astro, src/plugins/admin/index.ts, src/plugins/admin/overview.astro
currently, this looks like this on path `/admin/overview`
It contains styling as well as some type error
=> add: admin overview page

src/components/AdminMembershipsForm/AdminMembershipsForm.svelte, src/pages/sites_/[site]/setup/memberships/[id].astro
Adds a membership ID page to setup
=> adds the membership id page

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/AdminMembershipsForm/AdminMembershipsForm.svelte, src/components/AdminMembershipsForm/MembershipOption.svelte, src/components/WelcomeConnect/WelcomeConnect.svelte, src/fixtures/wallet/index.ts, src/layouts/Setup.astro, src/pages/api/addDaoToDraft.ts, src/pages/api/updateConfig.ts, src/pages/connect/[siteName].astro, src/pages/sites_/[site]/setup/memberships.astro, src/pages/sites_/[site]/setup/memberships/[id].astro, src/pages/sites_/[site]/setup/memberships/new/[preset].astro
=> [Clubs] Design patch: /setup/memberships

src/plugins/admin/index.ts
Directs it from "/admin", instead to "/admin/general"
=> admin index -> general

src/pages/authentication/[siteName].astro
Fix the param name variable and json data parsing in the authentication flow.
=> fix: authentication flow

src/fixtures/api/keys.ts, src/pages/api/addDaoToDraft.ts, src/pages/api/fetchClubs.ts
API endpoint that returns all club configs
=> api get all club configs

scripts/populate.mjs, src/fixtures/coingecko/api.ts, src/plugins/admin/AdminOverview.svelte, src/plugins/admin/overview.astro
=> [Clubs] Design path: /admin/overview

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/ProfileSetupForm/ProfileSetupForm.svelte, src/components/SetupDesign/SetupDesign.svelte, src/components/WelcomeConnect/WelcomeConnect.svelte, src/constants/defaultConfig.ts, src/layouts/Setup.astro, src/pages/sites_/[site]/setup/design.astro
=> [Clubs] Design patch for mobile screens: /setup/*

src/plugins/memberships/utils/example.ts, src/plugins/memberships/utils/simpleCollections.ts, src/plugins/memberships/utils/types/setImageArg.ts
=> Some improvements for SimpleCollections utils

src/components/UserClubs/UserClubItem.svelte, src/components/UserClubs/UserClubs.svelte, src/pages/api/fetchClubs.ts, src/pages/user/[id].astro
User page that displays published and draft clubs
=> user clubs page

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/pages/sites_/[site]/setup/memberships/[id].astro, src/pages/sites_/[site]/setup/memberships/new/[preset].astro, src/plugins/memberships/admin-id.astro, src/plugins/memberships/admin.astro, src/plugins/memberships/index.ts
=> impl: estimated earnings

src/pages/sites_/[site]/admin/[...page].astro
=> Add public-beta banner to admin pages

src/components/AdminThemeForm/AdminThemeForm.svelte
=> design patch for theme page

package.json, src/components/Domain/Domain.vue, src/components/EmailConnect/EmailConnect.svelte, src/components/ProfileSetupForm/ProfileSetupForm.svelte, src/components/SetupDesign/SetupDesign.svelte, yarn.lock
=> Style tweakings /1

package.json, src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/PublishConnect/PublishConnect.vue, src/components/PublishNetworkSelection/PublishNetworkSelection.vue, yarn.lock
=> Style tweakings /2

src/components/PublishNetworkSelection/PublishNetworkSelection.vue
Navigates to admin overview on successfully publishing
=> Navigates to admin overview on successfully publishing

src/components/Domain/Domain.vue, src/components/WelcomeConnect/WelcomeConnect.svelte, src/pages/authentication/[siteName].astro
=> Close the TODO comments: navigate to the next page

src/components/ProfileSetupForm/ProfileSetupForm.svelte, src/components/UserClubs/UserClubs.svelte, src/components/WelcomeConnect/WelcomeConnect.svelte, src/constants/draft.ts, src/layouts/Default.astro, src/layouts/Setup.astro, src/pages/authentication/[siteName].astro, src/pages/sites_/[site]/setup/publish.astro, src/plugins/memberships/index.ts
=> Fix the bug: setConfig on /setup/basic

src/fixtures/firebase/instance.ts, src/pages/api/addDaoToDraft.ts
```ts
import { instanceStore } from '@fixtures/firebase/instance'
const auth = instanceStore.initializedAdminApp
```
=> Fix Firebase instantiation issue on server-side

src/components/ProfileSetupForm/ProfileSetupForm.svelte
=> Margin to avatar

package.json, src/layouts/Default.astro, src/plugins/home/index.astro
=> Improve home page

src/components/WelcomeConnect/WelcomeConnect.svelte
=> fix(integration): update redirection link post welcome connect

src/components/Domain/Domain.vue
Resolve issue on Android where input not working.
=> testing for android

src/pages/[site]/setup/memberships/new/[preset].astro
Fixes location bug in setup/memberships/new/<preset>
=> fixes location bug

src/components/Domain/Domain.vue
=> caps off for iphone

astro.config.mjs, package.json, src/components/Members/Creators.vue, src/components/Sidebar/Sidebar.vue, src/fixtures/dev-kit/index.ts, yarn.lock
Fixes bug that occasionally crashes server on preview page
=> fixes bug on preview page that crashes server

src/components/PublishConnect/PublishConnect.vue, src/components/PublishNetworkSelection/PublishNetworkSelection.vue
=> updates copy on publish page

src/components/PublishNetworkSelection/PublishNetworkSelection.vue
=> fix(integration): update the logic of clubsx plugin page

package.json, scripts/flushDb.mjs, src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/ProfileSetupForm/ProfileSetupForm.svelte, src/layouts/Setup.astro
Fixes a bug where if the user didn't interact with the form, the default values would not save.
=> sets initial values on mount

src/plugins/buy/[id].astro, src/plugins/join/[id].astro, src/plugins/join/index.astro
Adds framework to missing client:only tags
=> adds framework to missing client:only tags

src/plugins/admin/AdminOverview.svelte, src/plugins/admin/index.astro, src/plugins/admin/overview.astro
=> fix(integration): change to client:only in admin plugins

src/pages/index.astro
=> Add link to Help & FAQs

src/pages/[site]/setup/memberships/new/[preset].astro
=> fix(integration): update baseUrl in [preset] membership setup

middleware.ts
=> fix middleware

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/ProfileSetupForm/ProfileSetupForm.svelte
=> fix: replace with explicit type imports

src/layouts/Default.astro, src/layouts/Setup.astro
=> feat(design): add favicon to layouts

src/pages/404.astro, src/pages/[site]/setup/basic.astro, src/pages/[site]/setup/design.astro, src/pages/[site]/setup/memberships.astro, src/pages/[site]/setup/memberships/[id].astro, src/pages/[site]/setup/memberships/new/[preset].astro, src/pages/[site]/setup/preview.astro, src/pages/[site]/setup/publish.astro, src/pages/sites_/[site]/[...page].astro, src/pages/sites_/[site]/admin/[...page].astro
=> feat(design): add a 404 page

src/components/AdminThemeForm/AdminThemeForm.svelte, src/pages/[site]/setup/preview.astro, src/plugins/admin/GeneralAdminForm.svelte
=> Fix build warnings

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/ProfileSetupForm/ProfileSetupForm.svelte, src/pages/[site]/setup/memberships/new/[preset].astro
=> fix: add some fixes to broken links, redirects, etc.

package.json, yarn.lock
=> chore(deps): update clubs-core to latest version

src/layouts/Setup.astro, src/pages/[site]/setup/basic.astro, src/pages/[site]/setup/design.astro, src/pages/[site]/setup/memberships.astro, src/pages/[site]/setup/memberships/[id].astro, src/pages/[site]/setup/memberships/new/[preset].astro, src/pages/[site]/setup/preview.astro, src/pages/[site]/setup/publish.astro
=> Titles and favicons in the setup flow

src/components/PublishNetworkSelection/PublishNetworkSelection.vue, src/plugins/join/[id].astro, src/plugins/join/index.ts, src/plugins/memberships/utils/simpleCollections.ts
=> Clubs is supporting only Polygon/Mumbai for now

src/components/AdminThemeForm/AdminThemeForm.svelte
=> fix(integration): allow updating configuration on addition/removal of links.

src/components/PublishNetworkSelection/PublishNetworkSelection.vue, src/plugins/memberships/admin-id.astro, src/plugins/memberships/admin-new.astro, src/plugins/memberships/utils/simpleCollections.ts, src/plugins/memberships/utils/types/setImageArg.ts
=> Change the Struct to follow the latest contract

src/constants/defaultConfig.ts, src/pages/coming-soon.astro, src/pages/sites_/[site]/admin/[...page].astro, src/plugins/admin/index.ts, src/plugins/marketplace/index.ts
=> feat(integration): add coming soon for marketplace admin page

src/components/AdminMembershipsForm/AdminMembershipsForm.svelte, src/components/AdminMembershipsForm/MembershipOption.svelte, src/pages/[site]/setup/memberships.astro, src/plugins/memberships/admin.astro
=> fix a bug that the creation form is not appeared on memberships

src/plugins/default-theme/components/Hero/Hero.astro, src/plugins/default-theme/pages/index.astro
- Add Clubs logo on the hero component
- Fix typo
=> add some fixings

package.json, yarn.lock
=> Fixes Admin Overview Link

src/layouts/Default.astro, src/pages/sites_/[site]/[...page].astro, src/pages/sites_/[site]/admin/[...page].astro
The global default layout (`@layouts/Default.astro`) adds the global UIs and scripts.
=> Add global default layout

src/components/PublishNetworkSelection/PublishNetworkSelection.vue, src/layouts/Setup.astro
=> feat(integration): update draft to false on publish step3.3 completion.

src/components/UserClubs/UserClubItem.svelte, src/components/UserClubs/UserClubs.svelte, src/pages/user/[id].astro
=> feat: update user/me page

scripts/populate.mjs, src/assets/homeConfig.kougenji.body.md, src/assets/homeConfig.temples.body.md, src/components/AdminMembershipsForm/MembershipOption.svelte, src/plugins/default-theme/components/Hero/Hero.astro, src/plugins/default-theme/components/Memberships/Memberships.astro, src/plugins/default-theme/layouts/Default.astro, src/plugins/fiat/index.astro, src/plugins/nft/index.astro
=> fix temples and kougenji

src/components/AddNavigationLink/AddNavigationLink.astro, src/components/AddNavigationLink/AddNavigationLink.svelte, src/plugins/community/index.ts, src/plugins/message/index.ts, src/plugins/quests/index.ts
=> impr: Add [text] to the menu buttons

src/components/Footer/Footer.astro, src/layouts/Default.astro, src/pages/index.astro
=> add the default footer to the default layout

src/plugins/memberships/admin-id.astro, src/plugins/memberships/admin-new.astro, src/plugins/memberships/index.ts, src/plugins/memberships/modal.astro
This change allows it to indicate what they need to send the transaction for to users.
=> Add modal to the admin page of `memberships`

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte
=> fixes bug blocking new memberships

src/plugins/memberships/admin-id.astro, src/plugins/memberships/admin-new.astro
Fixed bug with byte manipulation done via JSON API.
=> Fix broken bytes manipulation

src/plugins/admin/GeneralAdminForm.svelte, src/plugins/admin/index.astro, src/plugins/admin/index.ts
Fix bug where adminRolePoints wasn't present on general admin form
=> pass adminRolePoints

src/plugins/admin/GeneralAdminForm.svelte
=> checks input is below 100; removes note

src/components/UserClubs/UserClubItem.svelte
=> fix(integration): fix redirection link in users page

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte
=> fix(integration): fix membership price range input field

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte
=> fix(integration): fix issue with undefined in streaming info

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/AdminThemeForm/AdminThemeDesignForm.svelte
=> fix(integration): add theme form bug

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/AdminThemeForm/AdminThemeDesignForm.svelte, src/components/ProfileSetupForm/ProfileSetupForm.svelte
=> suggests image size in setup flow

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/AdminMembershipsForm/AdminMembershipsForm.svelte, src/components/AdminMembershipsForm/MembershipOption.svelte, src/pages/[site]/setup/memberships.astro, src/pages/[site]/setup/memberships/[id].astro, src/pages/[site]/setup/memberships/new/[preset].astro, src/plugins/default-theme/components/Memberships/Memberships.astro, src/plugins/default-theme/pages/index.astro, src/plugins/memberships/admin-id.astro, src/plugins/memberships/admin-new.astro, src/plugins/memberships/admin.astro, src/plugins/memberships/index.ts
=> Improved UX for membership editing

package.json, src/pages/[site]/setup/basic.astro, src/pages/[site]/setup/design.astro, src/pages/[site]/setup/memberships.astro, src/pages/[site]/setup/preview.astro, src/pages/[site]/setup/publish.astro, src/pages/sites_/[site]/admin/[...page].astro, src/plugins/community/index.ts, src/plugins/memberships/index.ts, src/plugins/message/index.ts, src/plugins/quests/index.ts, yarn.lock
Use `getSlots` API of the latest clubs-core.
=> Use the latest clubs-core

src/components/AdminThemeForm/AdminThemeForm.svelte
Related to https://www.pivotaltracker.com/story/show/184516140
=> adds ogp settings

src/pages/[site]/setup/basic.astro, src/pages/[site]/setup/design.astro, src/pages/[site]/setup/memberships.astro, src/pages/[site]/setup/preview.astro
=> fix(integration): fix next button slot in setup flow

package.json, yarn.lock
Tests rolling back Astro to see if it resolves API endpoint issues
=> rolls back astro update

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/AdminMembershipsForm/AdminMembershipsForm.svelte, src/components/AdminMembershipsForm/MembershipOption.svelte, src/plugins/default-theme/components/Header/Header.astro, src/plugins/default-theme/components/Hero/Description.svelte, src/plugins/default-theme/components/Hero/Hero.astro, src/plugins/default-theme/components/Hero/NumberOfMembers.svelte, src/plugins/default-theme/components/Memberships/Memberships.astro, src/plugins/default-theme/components/Navigation/Navigation.astro, src/plugins/default-theme/components/Share/Share.svelte, src/plugins/default-theme/index.ts, src/plugins/default-theme/layouts/Default.astro
=> New design for the default theme

src/pages/api/fetchClubs.ts, ugly.mjs
=> Debugging/fixing the API's 400 errors

src/fixtures/api/keys.ts, src/pages/api/plugins/addPluginToClub.ts
=> feat: add a structure to marketplace db.

src/constants/plugins.ts, src/pages/api/plugins/addPluginToClub.ts, src/pages/api/plugins/index.ts
=> feat: add a get api for fetching installable plugins

src/components/Dashboard/Basic.svelte, src/pages/api/stats.ts, src/pages/dashboard/index.astro
=> dashboard improvements

src/plugins/community/README.md, src/plugins/community/index.ts, src/plugins/default-theme/README.md, src/plugins/default-theme/index.ts, src/plugins/join/README.md, src/plugins/join/index.ts, src/plugins/me/README.md, src/plugins/me/index.ts, src/plugins/members/README.md, src/plugins/members/index.ts, src/plugins/memberships/README.md, src/plugins/memberships/index.ts, src/plugins/message/README.md, src/plugins/message/index.ts, src/plugins/quests/README.md, src/plugins/quests/index.ts
=> feat: add meta info to plugins

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/AdminThemeForm/AdminThemeDesignForm.svelte, src/components/Global/Banner.astro, src/components/PreviewBanner/PreviewBanner.svelte, src/components/ProfileSetupForm/ProfileSetupForm.svelte, src/layouts/Default.astro, src/layouts/Setup.astro, src/pages/[site]/setup/publish.astro, src/pages/api/updateDraftConfig.ts, src/pages/sites_/[site]/admin/[...page].astro, src/plugins/memberships/index.ts
=> UI tweaking

src/plugins/default-theme/components/Header/Header.astro, src/plugins/default-theme/components/Navigation/Navigation.astro, src/plugins/default-theme/index.ts, src/plugins/default-theme/layouts/Default.astro, src/plugins/default-theme/pages/index.astro
=> UI tweaking/ 2

src/constants/plugins.ts, src/plugins/community/index.ts, src/plugins/default-theme/index.ts, src/plugins/join/index.ts, src/plugins/marketplace/[pluginId].astro, src/plugins/marketplace/admin.astro, src/plugins/marketplace/components/PluginItem.astro, src/plugins/marketplace/index.ts, src/plugins/me/index.ts, src/plugins/members/index.ts, src/plugins/memberships/index.ts, src/plugins/message/index.ts, src/plugins/quests/index.ts
=> feat: add integration for marketplace/plugin.astro page

src/pages/authentication/[siteName].astro
=> fix: add missing url property for clubs created with email

src/components/AdminMembershipsForm/AdminMembershipsForm.svelte, src/components/AdminMembershipsForm/MembershipOption.svelte, src/components/PreviewBanner/PreviewBanner.svelte, src/components/SignInForm/SignInForm.svelte, src/components/WelcomeConnect/WelcomeConnect.svelte, src/components/WelcomeWizard/WelcomeWizard.svelte, src/layouts/Default.astro, src/pages/[site]/setup/design.astro, src/pages/sites_/[site]/[...page].astro, src/pages/sites_/[site]/admin/[...page].astro, src/plugins/default-theme/components/Hero/NumberOfMembers.svelte, src/plugins/default-theme/index.ts, src/plugins/default-theme/layouts/Default.astro, src/plugins/message/components/AdminForm.svelte
- ogp descriptions are abbreviated to improve readability
- fixed a bug that the preview banner was not displayed
=> UI tweaking for home

src/components/AddPluginButton/AddPluginButton.vue, src/constants/defaultConfig.ts, src/constants/plugins.ts, src/pages/api/plugins/addPluginToClub.ts, src/plugins/marketplace/[pluginId].astro
=> feat: add plugin to club integration

src/components/AddPluginButton/AddPluginButton.vue, src/components/Markdown/Markdown.astro, src/plugins/marketplace/[pluginId].astro, src/plugins/marketplace/components/PluginItem.astro
=> UI tweaking for marketplace single page

package.json, yarn.lock
Reverts dev-protocol/clubsx#732
=> Revert "fix(deps): update dependency astro to v2.1.7"

src/assets/Plugins/Feeds.svg, src/constants/plugins.ts, src/plugins/community/README.md, src/plugins/community/assets/icon.svg, src/plugins/community/index.ts, src/plugins/default-theme/README.md, src/plugins/default-theme/index.ts, src/plugins/join/README.md, src/plugins/join/assets/icon.svg, src/plugins/join/index.ts, src/plugins/marketplace/[pluginId].astro, src/plugins/marketplace/components/PluginItem.astro, src/plugins/marketplace/components/Wrapper.astro, src/plugins/marketplace/utils/createGetPluginMeta.ts, src/plugins/me/README.md, src/plugins/me/assets/icon.svg, src/plugins/me/index.ts, src/plugins/members/README.md, src/plugins/members/assets/icon.svg, src/plugins/members/index.ts, src/plugins/memberships/README.md, src/plugins/memberships/assets/icon.svg, src/plugins/memberships/index.ts, src/plugins/message/README.md, src/plugins/message/assets/icon.svg, src/plugins/message/index.ts, src/plugins/quests/README.md, src/plugins/quests/assets/icon.svg, src/plugins/quests/index.ts
=> feat: update dummy content plugins

src/components/Domain/Domain.vue
Notes (**optional**): We need to check more pages which import directly or indirectly web3modal for such errors.
=> fix: unwanted imports in domain page causing issues

src/components/AdminThemeForm/AdminThemeDesignForm.svelte, src/components/AdminThemeForm/AdminThemeForm.svelte, src/plugins/default-theme/index.ts
- Improved theme editor
- Added inks to default theme to accomodate for text readability from their respective backgrounds.
- Changed the delete color from standard to danger for better mental model.
- Have the inks persist to the actual club preview and the published club.
=> [UPDATE]: Improved theme editor

src/pages/api/decrypt.ts, src/plugins/message/components/AdminForm.svelte, src/plugins/message/pages/AdminEdit.astro, src/plugins/message/pages/AdminNew.astro, src/plugins/message/types.ts
=> Bugfixing and tweaking for gated-form

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/plugins/memberships/index.ts
=> Display peyload as string

src/components/Global/Banner.astro
Recommends users to leave feedback on Discord instead of our Airtable
=> refer to discord instead of airtable form

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte
Removes "Subscription Streaming" section from admin membership area.
https://www.pivotaltracker.com/n/projects/2631962
=> removes subscription streaming section

src/components/PublishNetworkSelection/PublishNetworkSelection.vue, src/pages/[site]/setup/publish.astro
=> Support a new URL flag

scripts/populate.mjs, src/constants/products.ts, src/plugins/fiat/Id.tsx, src/plugins/fiat/id.astro, src/plugins/fiat/index.ts
=> [Staging] Add crossmint integration

src/components/UserProfile/UserProfile.svelte, src/components/Wallet/ConnectButton.vue, src/fixtures/api/keys.ts, src/pages/api/profile/[id].ts, src/pages/api/profile/index.ts, src/pages/user/[id].astro
=> Add "Profile" page

package.json, src/layouts/Setup.astro, src/pages/sites_/[site]/admin/[...page].astro, yarn.lock
=> Debug save error

src/components/Checkout/Checkout.vue
Considering future maintainability, I rewrote `Checkout.vue`, where type inference is important, with Vue3.
=> Rewrite Checkout.vue in vue3 style

package.json, src/components/Checkout/Checkout.astro, src/components/Checkout/Checkout.vue, src/pages/api/mock/access-control.ts, src/plugins/join/index.ts, src/plugins/veritrans/index.ts, yarn.lock
Add: Access Control for Checkout flow
=> Add: Access Control for Checkout flow

src/plugins/tickets/Id.svelte, src/plugins/tickets/utils/date.ts
Make all Dayjs objects in UTC for code consistency.
=> Make all Dayjs objects in UTC for code consistency

src/components/Checkout/Checkout.vue, src/fixtures/dev-kit/index.ts
Checkout.vue is using SwapTokensAndStakeDev for any ERC20 pricing
** We must deploy https://www.pivotaltracker.com/n/projects/2631962/stories/185898071 before deploying this change.
=> Checkout.vue is using SwapTokensAndStakeDev for any ERC20 pricing

src/components/Checkout/Checkout.astro, src/components/Checkout/Checkout.vue, src/components/Checkout/Result.vue, src/fixtures/dev-kit/index.ts, src/plugins/veritrans/Id.astro, src/plugins/veritrans/TransactionForm.svelte, src/plugins/veritrans/api/fulfillment.ts, src/plugins/veritrans/api/payment-key.ts, src/plugins/veritrans/index.ts
Added better integration with Veritrans' fulfillment flow. 
However, I do not yet have their production access tokens, so I have not been able to implement the part of calling send.devprotocol.xyz from the fulfillment callback. 
=> Veritrans integration

package.json, src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/AdminMembershipsForm/SyncStatus.svelte, src/components/AdminMembershipsForm/types.ts, src/plugins/memberships/OpenModalButton.astro, src/plugins/memberships/OpenModalButton.svelte, src/plugins/memberships/SyncModal.astro, src/plugins/memberships/SyncModal.svelte, src/plugins/memberships/index.ts, src/plugins/memberships/modal.astro, src/plugins/memberships/utils/simpleCollections.ts, src/plugins/memberships/utils/types/setImageArg.ts, yarn.lock
Synchronize status on the membership edit page without sending on-chain transactions each time.
=> Better syncing system

src/plugins/tickets/api/post.ts, src/plugins/tickets/index.ts, src/plugins/tickets/utils/webhooks.ts
=> impl: webhook system for tickets

scripts/build-matcher.sh, scripts/ignored-builds.sh
=> Add  Ignored Build Step for Vercel

built-in-api-paths.js, src/fixtures/api/keys.ts, src/pages/api/shortify/[id].ts, src/pages/api/shortify/index.ts, src/pages/s/[id].astro
=> Add /api/shortify and add /s/[id]

package.json, src/constants/plugins.ts, src/plugins/marketplace/constants/modules.ts, yarn.lock
Adds Posts Plugin to Marketplace
=> adds posts plugin to marketplace

astro.config.mjs, package.json, src/components/Global/Navbar.vue, src/components/Wallet/ConnectButton.vue, src/layouts/BaseClubs.astro, src/layouts/Landing.astro, src/pages/sites_/[site]/[...page].astro, src/pages/sites_/[site]/admin/[...page].astro, src/plugins/default-theme/components/Header/Header.astro, src/plugins/default-theme/layouts/Default.astro, src/plugins/marketplace/[pluginId].astro, yarn.lock
=> Using the latest clubs-core to use Wallet Connect

astro.config.mjs
=> Fixed a bug that QR code was not rendered

src/components/AdminMembershipsForm/MembershipOption.svelte
=> Bugfix: Svelte `$:` reactivity doesn't work in the production

scripts/populate.mjs, src/components/Join/JoinClub.svelte, src/components/Wallet/ConnectButton.vue, src/constants/defaultConfig.ts, src/plugins/default-theme/components/Navigation/Navigation.astro, src/plugins/default-theme/layouts/Default.astro, src/plugins/join/index.astro, src/plugins/tickets/Index.svelte
- Improved Tickets loading performance
- Improved navigation menu for better visibility of Tickets
- Improved UI if the user doesn't have a ticket
=> Some UX improvements for Tickets

src/assets/accessControl.cryptocafe.description$1.md, src/assets/accessControl.cryptocafe.description$2.md, src/components/Checkout/Checkout.vue
If the description content has `{ACCOUNT}`, the placeholder will be replaced by the connected account address.
=> Supports prefill for accessControl.description

src/components/Checkout/Checkout.vue, src/fixtures/dev-kit/index.ts
=> Display warning when the user's token balance is insufficient

scripts/populate.mjs, src/components/Checkout/Checkout.astro, src/components/Checkout/Checkout.vue, src/components/Checkout/Result.vue, src/plugins/pay-by-card/id.astro, src/plugins/pay-by-card/index.ts, src/plugins/pay-by-card/slot.astro, src/plugins/veritrans/Id.astro, src/plugins/veritrans/index.ts, src/plugins/veritrans/slot.astro
=> Checkout UI improvements for mobile

src/components/Checkout/Checkout.astro, src/components/Checkout/Checkout.vue, src/plugins/pay-by-card/id.astro, src/plugins/pay-by-card/index.ts, src/plugins/pay-by-card/slot-currency-option.astro, src/plugins/pay-by-card/slot-currency-option.svelte, src/plugins/pay-by-card/utils/getItems.ts
=> Add "Credit Card" as a currency option

src/pages/sites_/[site]/admin/[...page].astro, src/plugins/marketplace/components/PluginItem.astro
- Fix plugin single page link
- Fix signin page link
=> Fix 2 broken links

.github/workflows/build.yml
Accelerate GitHub Actions by removing duplicate actions.
=> Ignore `yarn build` on github actions

scripts/populate.mjs, src/assets/homeConfig.cryptocafe.body.md
This PR is only for updating the configuration for CryptoCafe.
=> Configuration for CC

package.json, src/components/AdminMembershipsForm/AdminMembershipsForm.svelte, src/components/PreviewBanner/PreviewBanner.astro, src/pages/sites_/[site]/[...page].astro, src/pages/sites_/[site]/admin/[...page].astro, src/plugins/memberships/SyncModal.astro, src/plugins/memberships/SyncModal.svelte, src/plugins/memberships/admin.astro, yarn.lock
=> Fixed garbled character bug

scripts/populate.mjs, src/components/Checkout/Checkout.vue, src/plugins/clubs-payments/Id.astro, src/plugins/join/[id].astro, src/plugins/tickets/Id.svelte, src/plugins/tickets/i18n/index.ts, src/plugins/tickets/utils/date.ts
- Some tweaking
- Add simple i18n for Tickets
=> Tweaking uis

package.json, src/plugins/tickets/Id.svelte, src/plugins/tickets/Modal.svelte, src/plugins/tickets/i18n/index.ts, src/plugins/tickets/utils/date.ts, src/plugins/tickets/utils/status.ts, yarn.lock
Does check the expiration date before activating the ticket.
=> Ticket confirmation modal

src/components/PublishNetworkSelection/PublishNetworkSelection.vue
- Improved some UIs when `propertyMode === 'CONNECT'`
=> UI improvements for PublishNetworkSelection

src/components/Footer/Footer.astro, src/layouts/Default.astro, src/pages/sites_/[site]/[...page].astro, src/plugins/clubs-payments/index.ts, src/plugins/clubs-payments/slot-terms.astro
Adds VeriTrans terms of service if plugin is installed
=> dynamically adds veritrans terms in footer

src/plugins/admin/GeneralAdminForm.svelte
Removes "Danger Zone" in Admin->General 
=> Removes Danger Zone from Admin -> General

src/plugins/pay-by-card/slot.astro
=> Fix the bytes32 parsing error

src/plugins/admin/GeneralAdminForm.svelte
=> Add avatar edit form to `/admin/general`

package.json, src/pages/sites_/[site]/[...page].astro, src/pages/sites_/[site]/admin/[...page].astro, src/plugins/admin/index.ts, src/plugins/buy/index.ts, src/plugins/clubs-payments/index.ts, src/plugins/collections/index.ts, src/plugins/community/index.ts, src/plugins/default-theme/index.ts, src/plugins/home/index.ts, src/plugins/join-legacy/index.ts, src/plugins/join/index.ts, src/plugins/marketplace/index.ts, src/plugins/me/index.ts, src/plugins/members/index.ts, src/plugins/memberships/index.ts, src/plugins/message/index.ts, src/plugins/nft/index.ts, src/plugins/pay-by-card/index.ts, src/plugins/perks/index.ts, src/plugins/quests/index.ts, src/plugins/tickets/index.ts, yarn.lock
=> Using clubs-core v2.1

src/plugins/clubs-payments/i18n.ts, src/plugins/tickets/Id.svelte, src/plugins/tickets/i18n/index.ts
To make the code more readable, use `satisfies` to reduce key declarations.
=> Use TS `satisfies` instead of enum

src/plugins/admin/AdminOverview.svelte
Displays user and treasury token shares on the admin overview page.
=> Display User and Treasure Token Shares

src/plugins/default-theme/layouts/Default.astro
If a social link has an empty path, do not display it
=> hides empty social links

.github/workflows/build.yml, package.json, scripts/populate/cryptocafe.mjs, scripts/populate/validators/cryptocafe.mjs, scripts/populate/validators/cryptocafe.test.mjs, scripts/populate/validators/validatorFactory.mjs, scripts/populate/validators/validatorFactory.test.mjs, yarn.lock
- Added a common function `scripts/populate/validators/validatorFactory.mjs` for creating validators
- Added `scripts/populate/validators/cryptocafe.mjs` as the validator of CryptoCafe config using `validatorFactory`
- `yarn test` is now testing all validators of populate scripts
=> Add validators for populate scripts

src/plugins/clubs-payments/api/fulfillment.ts
The fulfillment flow of Clubs Payments requires that all transaction statuses are "success".
=> Update fulfilment flow: `status` and `m_status` must be `"success"`

package.json, yarn.lock
Temporarily downgrade web3modal as the dev server fails.
=> Downgrade web3modal

src/plugins/clubs-payments/api/fulfillment.ts
=> Add `requestId` option for calling send.devprotocol.xyz

src/components/Clarity/Clarity.astro, src/pages/sites_/[site]/[...page].astro, src/pages/sites_/[site]/admin/[...page].astro
=> Add Clarity integration

src/plugins/clubs-payments/api/fulfillment.test.ts, src/plugins/clubs-payments/api/fulfillment.ts
=> Add all test cases for Clubs Payments fulfillment flow

scripts/populate/cryptocafe.mjs, src/plugins/tickets/Id.astro, src/plugins/tickets/Id.svelte, src/plugins/tickets/Index.astro, src/plugins/tickets/Index.svelte, src/plugins/tickets/index.ts, src/plugins/tickets/utils/get-banning-rules.ts
Added a feature to ban specific NFT IDs to the Tickets plugin.
=> Tickets plugin: add banning feature.

package.json, yarn.lock
Reverts dev-protocol/clubsx#1679
=> Revert "fix(deps): update dependency @astrojs/vercel to v6"

src/plugins/admin/CurrencyMembershipInfo.tsx, src/plugins/admin/Funds.tsx, src/plugins/admin/FundsTeaser.tsx, src/plugins/admin/KYCInfo.tsx, src/plugins/admin/StakeInfo.tsx, src/plugins/admin/Withdrawal.tsx, src/plugins/admin/funds.astro
Links the withdrawal feature with KYC feature.
=> Feat link kyc withdrawal

src/plugins/admin/StakeInfo.tsx, yarn.lock
This pr enables showing correct dev amount in the staking section of funds page.
=> feat: fix dev staking 0 amount issue in ui

src/components/Collections/CollectionView.svelte, src/components/Collections/CreateCollections.svelte
- Replaced Form save button with `Add to Collection` this will make user click button and not confuse local state save with DB build via aside save button
- Fixed the input label width, which caused input trigger outside the file upload zone
- Tried debugging the promise error which caused processing circle keep going, turned out the issue is from metamask side only, and they are working on it to fix. 
- Couple of more other small UX fixes
=> Feat: UX improvement

src/plugins/admin/KYCInfo.tsx
=> fix: temp fix

src/components/Dashboard/Basic.svelte, src/pages/api/cron/updateStats.ts, src/pages/api/stats/types.ts
- updated cron job to add more data points
=> update: Dashboard with more data points

src/components/Dashboard/Basic.svelte, src/pages/api/cron/updateStats.ts, src/pages/api/stats/types.ts
Reverts dev-protocol/clubsx#1753
to check server load difference
=> Revert "update: Dashboard with more data points"

src/components/Dashboard/Basic.svelte, src/pages/api/cron/updateStats.ts, src/pages/api/stats/types.ts
Reverts dev-protocol/clubsx#1755
adding back the pull request
=> Revert "Revert "update: Dashboard with more data points""

vercel.json
Reverts dev-protocol/clubsx#1758
=> Revert "temp: cron scheduling to trigger vercel test cron"

src/plugins/admin/CurrencyMembershipInfo.tsx, src/plugins/admin/KYCInfo.tsx, src/plugins/admin/StakeInfo.tsx
- Addition of loading states, and message changes.
=> fix: minor improvements in KYC and withdrawal UX.

src/components/Collections/CreateCollections.svelte
Issue: Previously, attempting to edit memberships that were not yet saved resulted in page not found.
Resolution: Implemented checks to ensure only saved memberships are selectable for editing.
Issue: The size of the Membership Options was being distorted due to inappropriate grid column settings.
Improvement: Updated the grid grid-cols configuration to ensure consistent and visually appealing display of Membership Options across different devices and screen sizes.
=> Fix col save bug

src/components/Collections/CreateCollections.svelte, src/components/Domain/Domain.vue, src/components/Domain/i18n/index.ts, src/components/EmailConnect/EmailConnect.svelte, src/components/EmailConnect/i18n/index.ts, src/components/WelcomeConnect/WelcomeConnect.svelte, src/components/WelcomeConnect/i18n/index.ts
Adds localization to the domain and sign up pages
=> Domain localization

scripts/upgrade-posts-v2.mjs
Adds a migration script for posts v2
=> adds a posts upgrade script

package.json, scripts/upgrade-posts-v2.mjs
updates script to migrate posts
=> find plugin by id rather than name

scripts/upgrade-posts-v2.mjs
- Fixed an issue where Posts plugin options were not updated
- Changed to keep the old option values with `slug: "_old_default_feed"`.
=> Fix some bugs in scripts/upgrade-posts-v2.mjs

scripts/upgrade-posts-v2.mjs
=> drops existing posts indexes

src/components/AdminMembershipsForm/MembershipOption.svelte
Fixes the issue where images when uploaded are saved but not visible and not updated in the UI component.
=> fix: membership image upload loading issue

src/components/Collections/CollectionView.svelte
=> fix: avoid getSlot call when membership == 0 

src/plugins/collections/utils/slotCollections.ts
update collections contract address
=> updated: contract address for slotCollections on Mumbai & polygon pos mainnet

package.json, scripts/upgrade-posts-v2.mjs, src/components/Collections/CollectionView.svelte, src/components/Domain/Domain.vue, src/components/Domain/i18n/index.ts, src/components/EmailConnect/EmailConnect.svelte, src/components/EmailConnect/i18n/index.ts, src/components/WelcomeConnect/WelcomeConnect.svelte, src/components/WelcomeConnect/i18n/index.ts, src/plugins/collections/utils/slotCollections.ts, yarn.lock
=> Release 12272023

src/fixtures/flags/index.ts, src/plugins/admin/funds.astro, src/plugins/marketplace/admin.astro
Removes feature flags for Shops and KYC
=> removes feature flag requirements for shops and kyc

src/constants/plugins.ts
updates db type to documents:redis
=> updates db type to documents:redis

src/constants/plugins.ts
Use pure UUIDs as scopes to account for possible query bugs in Posts. 
=> Use just UUID as a scope

src/constants/plugins.ts
=> update: Clubs Shop display

package.json, yarn.lock
Reverts dev-protocol/clubsx#1849
=> Revert "rollback wagmi update to debug erroring club"

package.json, src/pages/api/verifySiteName/[...site].ts, yarn.lock
Restricts profanity in domain names
=> checks for profanity in domain

src/components/AdminMembershipsForm/AdminMembershipsForm.svelte, src/components/AdminMembershipsForm/i18n/index.ts, src/components/AdminThemeForm/AdminThemeDesignForm.svelte, src/components/AdminThemeForm/AdminThemeForm.svelte, src/components/AdminThemeForm/i18n/index.ts, src/components/ProfileSetupForm/ProfileSetupForm.svelte, src/components/ProfileSetupForm/i18n/index.ts
Adds localization for more of the setup flow
=> Club setup localization

.github/workflows/build.yml, .github/workflows/deploy.yml, src/components/Global/Banner.astro, src/components/Membership/Membership.vue, src/components/ProfileSetupForm/i18n/index.ts, src/plugins/admin/KYCInfo.tsx, src/plugins/collections/utils/slotCollections.ts, src/plugins/home/index-for-temples.astro, src/plugins/memberships/utils/erc20SimpleCollections.ts, src/plugins/memberships/utils/simpleCollections.ts, src/plugins/tickets/utils/get-minted-at.ts, vercel.json
Instead of deploying `main` and `release`, deploy when there is a new tag.
https://vercel.com/guides/can-you-deploy-based-on-tags-releases-on-vercel for reference.
=> deploy by tagged release

package.json
bumps version to 0.12.0--beta.1 to test new deployment flow
=> bumps version to beta.1

.github/workflows/deploy.yml, package.json
Debugging GitHub action error related to Vercel environments
=> updates deployment vercel environment

.github/workflows/deploy.yml, package.json
Specify deploy target in github action
=> Bump version

.github/workflows/deploy.yml, package.json
deploy to development instead of preview
=> deploy to development instead of preview

.github/workflows/deploy.yml
=> `--prod` option is ignored when prerelease

.github/workflows/deploy.yml, package.json
adds space in case empty string is falsy
=> adds space in case empty string is falsy

package.json
Bumps version for testing production deployment
=> bumps to version 0.12.1

.github/workflows/deploy.yml, package.json
separate deploy and conditional alias actions
=> separate deploy and conditional alias actions

.github/workflows/deploy.yml, package.json
scopes alias; adds wildcard alias
=> scopes alias; adds wildcard alias

package.json, src/plugins/home/index.astro
testing if prerelease is truly aliasing
=> testing if prerelease is truly aliasing

package.json, src/components/PublishConnect/PublishConnect.vue, src/components/PublishConnect/i18n/index.ts, src/components/PublishNetworkSelection/PublishNetworkSelection.vue, src/components/PublishNetworkSelection/i18n/index.ts, yarn.lock
localization for publish network component
=> localization for publish network component

src/plugins/invitations/handlers/post-invitation.ts, src/plugins/invitations/redis-schema.ts
Add POST endpoint to create a new invitation
=> Add POST endpoint to create a new invitation

package.json, src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/AdminMembershipsForm/AdminMembershipsForm.svelte, src/components/Collections/CollectionView.svelte, src/components/Collections/CreateCollections.svelte, src/components/PublishNetworkSelection/PublishNetworkSelection.vue, src/fixtures/utility.ts, src/plugins/clubs-payments/api/payment-key.ts, src/plugins/collections/index.ts, src/plugins/join-legacy/index.ts, src/plugins/join/index.ts, src/plugins/memberships/SyncModal.svelte, src/plugins/memberships/index.ts, src/plugins/memberships/utils/is.ts, src/plugins/message/components/AdminForm.svelte, src/plugins/pay-by-card/Id.tsx, src/plugins/pay-by-card/id.astro, src/plugins/pay-by-card/utils/getItems.ts, yarn.lock
- Instead of adding `isUnpriced` field, `price` and `currency` now support undefined.
- Add `isUnpriced(Membership)` and `isPriced(Membership)` functions.
- With this, I was able to detect the need for UI/API changes due to changes in Membership type, and I fixed them.
These are based on the idea of avoiding the addition of fields that are essentially explainable only by the state of the values, and getting explanations from the state by means of utility functions. 
=> Unpriced memberships that using `undefined`/ Add `isUnpriced()` `isPriced()` functions

src/plugins/invitations/handlers/post-invitation.ts
checks if id exists before inserting a new invitation
=> checks if id exists before inserting a new invitation

src/components/AdminThemeForm/AdminThemeDesignForm.svelte, src/components/AdminThemeForm/i18n/index.ts
=> feat: add localization of sectionsOrder

package.json, src/plugins/invitations/handlers/post-invitation.ts, src/plugins/invitations/index.ts
Adds the post invitation endpoint
=> adds handler for posting invitation

package.json, src/plugins/invitations/handlers/post-invitation.ts
fixes small bug in post invitation handler
=> fixes small bug in post invitation handler

package.json, src/constants/plugins.ts
adds invitations to plugins list
=> adds invitations to plugins list

package.json, src/plugins/invitations/README.md, src/plugins/invitations/assets/icon.svg, src/plugins/invitations/index.ts
fixes invitations build errors
=> fixes invitations build errors

src/plugins/invitations/handlers/post-invitation.ts, src/plugins/invitations/index.ts
adds authentication for invitations
=> adds authentication for invitations

src/components/AddPluginButton/AddPluginButton.vue, src/components/UserProfile/UserProfile.svelte, src/components/WelcomeConnect/WelcomeConnect.svelte, src/layouts/Landing.astro, src/layouts/Setup.astro, src/pages/sites_/[site]/admin/[...page].astro, src/plugins/admin/KYCInfo.tsx, src/plugins/message/components/AdminForm.svelte, src/plugins/message/components/MessageForm.vue, src/plugins/tickets/Id.svelte
Some wallets (i.g., Bitget Wallet) cannot parse a Byteslike string as a message to sign.
=> Use utf8 string to sign

package.json, src/constants/plugins.ts, src/pages/sites_/[site]/admin/[...page].astro, src/plugins/admin/GeneralAdminForm.svelte, src/plugins/marketplace/constants/modules.ts, yarn.lock
- Install @devprotocol/clubs-core@3.6.0
- Update the typing of `ClubsConfiguration.adminPageVisibility` to follow the latest version
- UI updates
=> Install the latest clubs-core

package.json, src/plugins/default-theme/components/Navigation/Navigation.astro, src/plugins/default-theme/layouts/Default.astro
=> Fix a bug where navigation links would break lines.

package.json, yarn.lock
Install @devprotocol/clubs-core@3.7.0
=> Install @devprotocol/clubs-core@3.7.0

src/plugins/admin/CurrencyMembershipInfo.tsx
=> Fix a bug where UI is not updated when updating wallet connection

src/constants/plugins.ts, src/plugins/achievements/handlers/addAchievement.ts, src/plugins/achievements/utils.ts
=> feat: add achievements page ui

src/fixtures/flags/index.ts, src/plugins/marketplace/admin.astro
=> Add feature flag for enabling Achievements on marketplace.

package.json, scripts/populate/aggre-demo-std-2.mjs, src/plugins/tickets/Id.astro, src/plugins/tickets/Id.svelte, src/plugins/tickets/Index.astro, src/plugins/tickets/Index.svelte, src/plugins/tickets/Slot.astro, src/plugins/tickets/api/get.ts, src/plugins/tickets/api/post.ts, src/plugins/tickets/index.ts, src/plugins/tickets/utils/api.ts, src/plugins/tickets/utils/gen-key.ts, src/plugins/tickets/utils/get-minted-at.ts, src/plugins/tickets/utils/nft.ts, src/plugins/tickets/utils/status.ts, yarn.lock
Tickets plugin is now supporting arbitrary NFT contracts. This will allow SBTs minted by Achievements plugin to be used as tickets.
=> Initial implementation for SBT Tickets

package.json, src/components/Join/JoinClub.svelte, src/fixtures/utility.ts, src/plugins/join/index.ts, yarn.lock
Fixed a bug that prevented the Join plugin from working in unpriced memberships.
=> Fix a bug on unpriced memberships

src/plugins/achievements/handlers/claimAchievement.ts
=> feat: add logic to mint sbt

src/plugins/achievements/components/Achievement.svelte
=> UI tweaking for Achievements

src/constants/plugins.ts, src/plugins/achievements/handlers/addAchievement.ts, src/plugins/achievements/handlers/fetchAchievementId.ts, src/plugins/achievements/index.ts, src/plugins/achievements/pages/[id].astro, src/plugins/achievements/utils.ts
Remove `PLUGIN_ACHIEVEMENT_IDS_OPTION_KEY` options and using RegExp path instead of precalculated path.
=> Using RegExp path instead of precalculated path

src/components/Global/Skeleton.vue, src/plugins/achievements/components/Achievement.vue, src/plugins/achievements/pages/[id].astro
=> feat: use vue component in ui

src/constants/plugin-tags.ts, src/constants/plugins.ts, src/plugins/marketplace/admin.astro, src/plugins/marketplace/components/Nav.svelte, src/plugins/marketplace/utils/createGetPluginMeta.ts
Fixed a hydration error on the Marketplace page. The problem was caused by an indirect reference to server-side libraries (such as redis) that occurred when the front-end components imported `@constants/plugins`. 
=> Fix a bug on marketplace

src/components/AdminMembershipsForm/i18n/index.ts, src/components/PublishNetworkSelection/i18n/index.ts, src/plugins/tickets/i18n/index.ts
=> updates japanese language copy

package.json, src/constants/plugins.ts, src/fixtures/flags/index.ts, src/plugins/marketplace/admin.astro, src/plugins/marketplace/constants/modules.ts, yarn.lock
=> add: Real Time Communication (RTC) plugin with post form schedule functionality 

src/fixtures/api/club/redis.ts, src/pages/api/addDaoToDraft.ts, src/pages/api/clubs.ts, src/pages/passport/[id]/clubs.astro, src/pages/passport/components/UserClubs.svelte
Removes the user: [club] setter in addDaoToDraft. This is now handled with the passport updates.
=> removes setting of user clubs, which is now handled in api/clubs

src/components/PublishConnect/PublishConnect.vue, src/components/PublishConnect/i18n/index.ts, src/components/PublishNetworkSelection/PublishNetworkSelection.vue, src/components/PublishNetworkSelection/i18n/index.ts
Removes some copy Kent requested to be removed. 
=> removes some copy requested to be removed

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/AdminMembershipsForm/i18n/index.ts
Adds some missing Japanese support for the membership form
=> adds i18n to membership form

src/plugins/achievements/components/Achievement.svelte
Add Achievement Type in the achievements claim page UI.
=> feat: add type in achievements ui

package.json, src/fixtures/api/club/redis.ts
- Use escaped character searching while creating clubs using wallet.
=> fix: clubs connect using wallet after domain selection

package.json, scripts/create-invitation.mjs, src/plugins/invitations/components/ClaimButton.svelte, src/plugins/invitations/handlers/post-invitation.ts, src/plugins/invitations/redis-schema.ts
=> Use "conditions.recipients" as an array of TEXT instead of "conditions.recipient"

package.json, src/constants/plugins.ts, src/plugins/marketplace/admin.astro, src/plugins/marketplace/constants/modules.ts, yarn.lock
=> feat: comment dynamic wallet plgn files for now

src/plugins/achievements/components/Achievement.svelte, src/plugins/achievements/db/schema.ts, src/plugins/achievements/handlers/addAchievement.ts, src/plugins/achievements/handlers/claimAchievement.ts, src/plugins/achievements/handlers/fetchAchievementId.ts, src/plugins/achievements/index.ts, src/plugins/achievements/types.ts
- Add clubs to save, fetch, and update achievements item.
=> feat: add clubs in achievements api.

src/pages/api/addDaoToDraft.ts, src/pages/api/profile/[id]/assets.ts, src/pages/api/updateConfig.ts, src/pages/api/updateDraftConfig.ts
Fixed a bug failing ClubsConfigutation updates if the index on which `@fixtures/api/club/redis` depends was not yet created.
=> Fixed a bug failing ClubsConfigutation updates if the index on which `@fixtures/api/club/redis` depends was not yet created.

package.json, yarn.lock
Install @devprotocol/clubs-plugin-posts@0.20.0
=> Install @devprotocol/clubs-plugin-posts@0.20.0

package.json, src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte, src/components/AdminMembershipsForm/i18n/index.ts, src/env.d.ts, src/pages/[site]/setup/memberships/[id].astro, src/pages/[site]/setup/memberships/new/[preset].astro, src/plugins/memberships/admin-id.astro, src/plugins/memberships/admin-new.astro
Add missing links to various texts in add/edit memberships page.
- [•] Added description of the change
- [•] I've read the [contributing guidelines](https://github.com/WebXDAO/devprotocol.xyz/blob/main/CONTRIBUTING.md)
- [•] Search previous suggestions before making a new PR, as yours may be a duplicate.
- [•] I acknowledge that all my contributions will be made under the project's license.
=> feat: add missing link to credit card plgn in memberships

src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte
Modify the underline text for credit card plugin in membership edit/add page.
=> feat: modify underline text in membership page

src/constants/plugins.ts, src/fixtures/flags/index.ts, src/plugins/marketplace/admin.astro, src/plugins/marketplace/constants/modules.ts
=> tweak list of marketplace

package.json, src/plugins/invitations/components/ClaimButton.svelte
=> fixes claim invitation bug

package.json, yarn.lock
=> bumps clubs core

package.json, yarn.lock
Bumps version of posts plugin with redis reconnect removed and connection timeout added
=> bumps version of posts plugin

scripts/redis-info.mjs
Adds a script to give us the info on the connected redis db
=> adds a script to get redis info

scripts/redis-info.mjs
Updates the redis monitoring script to ping info every second + log time on change of number of connections
=> ping info every second + log time on change of number of connections

package.json, src/plugins/achievements/utils.ts
=> quits redis client after use

src/pages/api/profile/[id]/index.ts
- Profile API will cache identical requests for 30 seconds.
=> Add cache header to /profile API

package.json, src/pages/api/profile/[id]/index.ts
Fixes an issue when a profile was not found, it was returning an empty object.
Now returning a 404 with an error
=> Profile undefined

scripts/redis-kill-connections.mjs
script to kill all redis connections
=> Redis kill connections script

package.json, yarn.lock
=> updates posts plugin

package.json, yarn.lock
=> bumps posts plugin

package.json, yarn.lock
Bumps posts version, which supports emoji toggling
=> bumps posts

src/components/PublishNetworkSelection/PublishNetworkSelection.vue, src/plugins/invitations/handlers/claim-invitation.ts, src/plugins/memberships/SyncModal.svelte
uses membership struct related to https://devprtcl.atlassian.net/browse/CLUB-115
=> uses membership struct

package.json, src/plugins/admin/AdminOverview.svelte
removes sig request in admin overview
=> removes sig request in admin overview

package.json, yarn.lock
install @devprotocol/clubs-core@3.12.8
=> install @devprotocol/clubs-core@3.12.8

src/plugins/tickets/api/post.ts
Add error handling: Error handling in the Tickets Post API to avoid interrupting the process even if an incorrect JWT token is used.
=> Add error handling: Tickets Post API

package.json, src/plugins/invitations/i18n/index.ts
=> Fix invitations localization

src/components/Collections/CollectionCard.svelte, src/components/Collections/CollectionView.svelte
Added markdown support to Shop.
=> Shop supports markdown descriptions

package.json, src/components/AdminMembershipsForm/MembershipOption.svelte, src/components/Collections/CollectionView.svelte, src/components/Markdown/Markdown.astro, src/plugins/collections/admin.astro, src/plugins/tickets/Id.svelte, yarn.lock
=> Use `markdownToHtml` from clubs-core

package.json, src/components/Collections/CreateCollections.svelte, yarn.lock
- fixes clubs shop sale end duration bug
=> fix: collection sale end duration reset bug

src/components/Collections/CreateCollections.svelte, src/constants/memberships.ts
This PR simplifies the shop plugin. It removes the need for earning model (the UI is commented out) and ensures 0% staking in shops plugin.
=> feat: add 0% staking in clubs shop and removing the balancing UI from it.

src/components/WelcomeConnect/WelcomeConnect.svelte, src/pages/connect/[siteName].astro
I've replaced the old connection structure with Dynamic wallet.
=> Replace old connection structure with Dynamic wallet

src/components/AdminThemeForm/AdminThemeForm.svelte
=> Fixed a bug where Nagivation Links could not be deleted

package.json, src/plugins/tickets/Index.svelte, src/plugins/tickets/i18n/index.ts
=> Feat localization

src/components/AdminThemeForm/AdminThemeDesignForm.svelte, src/components/AdminThemeForm/i18n/index.ts, src/plugins/collections/checkout.astro, src/plugins/default-theme/components/Hero/Hero.astro, src/plugins/default-theme/index.ts, src/plugins/default-theme/layouts/Default.astro
- Members Count Visibility switch
| <img width="436" alt="Screenshot 2024-07-08 at 3 11 00 PM" src="https://github.com/dev-protocol/clubsx/assets/57281769/05cb8564-9287-4937-898a-047804b24af8"> | <img width="983" alt="Screenshot 2024-07-08 at 3 19 06 PM" src="https://github.com/dev-protocol/clubsx/assets/57281769/cd612a5e-d922-46f6-9c2d-7e675565608c"> |
| -------- | -------- | 
| <img width="381" alt="Screenshot 2024-07-08 at 3 20 42 PM" src="https://github.com/dev-protocol/clubsx/assets/57281769/383adaa1-6452-458b-b60a-3b3507fdebe4">    | <img width="923" alt="Screenshot 2024-07-08 at 3 21 22 PM" src="https://github.com/dev-protocol/clubsx/assets/57281769/6ff49434-90be-484d-add5-d7494fc068d1">     |
=> Add: Members Count

src/components/AdminMembershipsForm/MembershipOption.svelte, src/components/AdminMembershipsForm/i18n/index.ts, src/plugins/clubs-payments/Id.astro, src/plugins/clubs-payments/slot.astro, src/plugins/clubs-payments/utils/create-path.ts, src/plugins/default-theme/components/Memberships/Memberships.astro, src/plugins/default-theme/index.ts, src/plugins/default-theme/pages/index.astro
- If the club uses Clubs Payments, the default theme will use these override pricing as the price/currency for the membership list.
- Checkout page of Clubs Payments now has a link to a checkout page using source pricing.
=> Default theme prioritizes Clubs Payments pricing

package.json, src/components/Admin/Resources.astro, src/components/Icons/bell-alert.astro, src/components/Icons/book-open.astro, src/components/Icons/chat-bubble-oval-left-ellipsis.astro, src/components/Icons/code-bracket.astro, src/components/Icons/question-mark-circle.astro, src/pages/sites_/[site]/admin/[...page].astro, yarn.lock
|dark|light|
|-|-|
|![Screenshot_11-7-2024_104530_aggre-demo-std-2 localhost](https://github.com/dev-protocol/clubsx/assets/1970283/0b048cc4-56ec-4482-8291-3d86c1f519fd)|![Screenshot_11-7-2024_104543_aggre-demo-std-2 localhost](https://github.com/dev-protocol/clubsx/assets/1970283/246557d3-2fd7-4966-914a-35c0110d7446)|
=> Resource links on the admin sidebar

src/pages/signin.astro
=> Remove the navigation to /domain from signin page

package.json, src/components/AdminMembershipsForm/i18n/index.ts
=> Fix memberships localization

src/plugins/default-theme/components/Memberships/Memberships.astro, src/plugins/default-theme/i18n/index.ts
=> add i18n for clubs payments in default-theme

scripts/create-achievement.mjs, src/pages/api/profile/[id]/assets.ts, src/plugins/achievements/components/Achievement.svelte, src/plugins/achievements/db/redis.ts, src/plugins/achievements/db/schema.ts, src/plugins/achievements/handlers/addAchievement.ts, src/plugins/achievements/handlers/claimAchievement.ts, src/plugins/achievements/handlers/fetchAchievementId.ts, src/plugins/achievements/types.ts, src/plugins/achievements/utils.ts
Achievements now supports a single ID with multiple recipients. (`recipients` or `maxRedemptions`)
=> Achievements support multiple recipients/maxRedemptions

astro.config.mjs, package.json, vercel.json, yarn.lock
Set default maxDuration to 300.
=> Set maxDuration:300

astro.config.mjs, vercel.json
=> Change the way to define maxDuration

src/fixtures/api/assets/schema.ts, src/fixtures/api/assets/utils.ts, src/pages/api/assets/related/account/[account]/index.ts
=> Add /api/assets/related/account/[account] endpoint

src/fixtures/nft.ts, src/pages/passport/[id].astro, src/pages/passport/components/UserAsset.vue, src/pages/passport/components/UserAssets.vue
=> Passport uses the Assets API

built-in-api-paths.js, src/components/SuperUser/Page.vue, src/components/SuperUser/utils/achievements.ts, src/components/SuperUser/utils/index.ts, src/constants/superuser.ts, src/fixtures/api/superuser/index.ts, src/pages/api/superuser/achievements.ts, src/pages/api/superuser/config.ts, src/pages/superuser/index.astro, src/plugins/achievements/handlers/addAchievement.ts
Superuser page allows us to update/create some data for internal use.
=> Superuser page

.github/workflows/deploy-preview.yml, .github/workflows/deploy.yml
=> Using node 20.x for deploy.yml and deploy-preview.yml

src/components/PublishConfirm/PublishConfirm.svelte, src/components/PublishConfirm/i18n/index.ts
=> feat: add logic to smoothen the ux of onboarding flow

package.json, yarn.lock
install @devprotocol/clubs-core@3.18.0
=> install @devprotocol/clubs-core@3.18.0

package.json, src/constants/plugins.ts, src/fixtures/api/assets/utils.ts, src/fixtures/flags/index.ts, src/pages/api/cron/assets.ts, src/plugins/marketplace/constants/modules.ts, yarn.lock
=> Feat add passport plugin

src/pages/passport2/Layout.astro, src/pages/passport2/[id].astro, src/pages/passport2/[id]/clubs.astro, src/pages/passport2/[id]/edit.astro, src/pages/passport2/components/Icons.vue, src/pages/passport2/dummyData.css
- Added some fixed CSS class names.
- Tweaked styles.
=> Passport Skins: Complete HTML the part above the pinned assets

src/pages/passport/components/UserAsset.svelte, src/pages/passport/components/UserProfileEdit.svelte, src/pages/passport/components/UserProfileEditButton.svelte, src/pages/passport/i18n/index.ts
=> feat: improve some UX features

src/pages/passport/Layout.astro, src/pages/passport/[id].astro, src/pages/passport/[id]/clubs.astro, src/pages/passport/[id]/edit.astro, src/pages/passport/components/Icons.vue, src/pages/passport/components/ImageCard.vue, src/pages/passport/components/PassportAsset.svelte, src/pages/passport/components/PassportClips.vue, src/pages/passport/components/UserAsset.vue, src/pages/passport/components/UserAssets.vue, src/pages/passport/components/UserProfileEdit.svelte, src/pages/passport/components/UserProfileEditButton.svelte, src/pages/passport/i18n/index.ts, src/pages/passport/types.ts, src/pages/passport/utils.ts
=> Feat passport perf

src/pages/passport/components/UserProfileEdit.svelte
=> Fix passpor asset pinning

src/pages/passport/components/ImageCard.vue, src/pages/passport/components/Modal.vue, src/pages/passport/components/PassportClip.vue, src/pages/passport/components/PassportClips.vue
=> Modal impl for Passport clips

src/pages/passport/[eoa]/[...ids]/index.astro
- it adds spotlights. also keeps the count max to three only
https://github.com/dev-protocol/clubsx/compare/main...KukretiShubham:clubsx:spotlight?expand=1#diff-c235fdb6aa968a5ca46532c78406585f93c1c8eda56619076924756aaceace17R120
=> add: only 3 spotlights

src/components/Global/Header.astro, src/pages/passport/Layout.astro, src/pages/passport/[eoa]/[...ids]/index.astro, src/pages/passport/[id]/edit.astro, src/pages/passport/components/PassportClip.vue, src/pages/passport/components/PassportClips.vue, src/pages/passport/components/SkinSwitch.svelte, src/pages/passport/components/UserProfileEdit.svelte, src/pages/passport/components/UserProfileEditButton.svelte
- Add some CSS tweakings.
- Add multiple skins support in the edit UI.
- Fix clips and spotlight duplication on modal click.
=> feat: support multiple skins in edit ui

src/pages/passport/components/MediaCard.vue
=> fix: minor fixes

src/pages/passport/[eoa]/[...ids]/index.astro, src/pages/passport/components/PassportClip.vue, src/pages/passport/components/PassportClips.vue
This is because Astro doesn't pass hash into it's SSR.
=> fix: update the share url to use path rather than hash in url construction.

astro.config.mjs, package.json, yarn.lock
=> fix: bump yaml package

src/constants/defaultConfig.ts, src/fixtures/api/feed/index.ts, src/fixtures/api/profile/utils.ts, src/pages/api/feed/index.ts
- Get feed for passport items purchased.
=> feat: add API for feeds.

package.json, src/fixtures/api/feed/index.ts, src/pages/api/feed/index.ts, yarn.lock
remove limits from db call and update akiba plugin.
=> fix: remove limit from feeds

src/pages/api/profile/index.ts, src/pages/passport/components/EditPagePurchasedClips.svelte, src/pages/passport/components/EditPassportSkinShowcase.svelte, src/pages/passport/components/EditPassportSkinSpotlight.svelte, src/pages/passport/types.ts
Added creation/modification times to types for UGC support and making more seamless feeds.
=> Add `createdAt/updatedAt` field for Profile.Skins[].clips

package.json, src/fixtures/api/profile/utils.ts, yarn.lock
=> Implement default pretty-username

astro.config.mjs
Without disabling this, updating settings from the admin pages will not work.
=> Disable AstroConfig.security.checkOrigin

src/fixtures/config.ts, src/fixtures/site.ts, src/pages/api/verifySiteName/[...site].ts, src/pages/sites_/[site]/[...page].astro
=> Fixed a bug when receiving a request with an unexpected path

src/components/Global/Header.astro, src/components/Global/NavbarResponsive.vue, src/pages/passport/Layout.astro, src/pages/passport/[id]/edit.astro, src/pages/passport/components/PostButton.vue, src/pages/passport/components/UserProfileEdit.svelte, src/pages/passport/i18n/index.ts
- Add "Post" button on the header of passport editing page.
=> Add "Post" button to the header

package.json, src/components/Feed/Feed.vue, src/components/Feed/FeedPageContent.vue, src/components/Global/Footer.vue, src/components/Global/NavbarResponsive.vue, src/fixtures/api/feed/index.ts, src/layouts/LandingWithFooter.astro, src/pages/passport/components/MediaCard.vue, src/pages/passport/components/PassportAsset.svelte, yarn.lock
=> feed implementations

src/fixtures/ui/passport.ts, src/fixtures/url/passports.ts, src/pages/passport/Layout.astro, src/pages/passport/[eoa]/[...ids]/index.astro
=> Tweak passport default look

src/components/Feed/Feed.vue, src/pages/passport/components/MediaCard.vue
=> Tweak feed

package.json, scripts/fill-edge-config.mjs, src/fixtures/api/club/redis.ts, src/fixtures/config.ts, yarn.lock
Synchronize the tenant IDs to the vercel Edge Config and block an unexpected path without establishing a Redis connection.
=> Middleware blocks unexpected requests

built-in-api-paths.js, src/components/Feed/FeedPageContent.vue, src/components/Home/Frontpage.vue, src/constants/cookie.ts, src/constants/feeds.ts, src/fixtures/api/feed/index.ts, src/pages/api/feed/index.ts, src/pages/index.astro
=> add tag with array

src/pages/passport/Layout.astro
=> add default skin settings

package.json, src/assets/clubs/cards.svg, src/constants/passports.ts, src/fixtures/router/passportItem.ts, src/pages/og/image/passport/[eoa]/[passportId]/[...item]/components/Description.vue, src/pages/og/image/passport/[eoa]/[passportId]/[...item]/components/ItemView.astro, src/pages/og/image/passport/[eoa]/[passportId]/[...item]/index.astro, src/pages/passport/Layout.astro, src/pages/passport/components/Onboarding.vue, yarn.lock
=> Passport ogp tweak

src/components/Feed/FeedPageContent.vue, src/fixtures/api/feed/index.ts
This PR fixes the issue of parallel inserts in array when using array.push with Promise.all. We are now rather using array.flat to denest all nested items in the array.
=> fix: use flat array rather than push in array

src/pages/passport/components/PassportClipEditModal.svelte
| Before | After |
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/16448fe0-fcd3-4a04-9e51-19818b2ed6ec) | ![After](https://github.com/user-attachments/assets/ef54d851-1c42-4306-821c-d4eef76437d8) |
=> fix: Move Done to the Unlist area and move Unlist to the left

package.json, src/fixtures/api/feed/index.ts, src/fixtures/api/profile/index.ts, src/pages/api/assets/related/account/[account]/index.ts, src/pages/api/assets/related/account/[account]/passportItems.ts, src/pages/api/assets/related/property/[propertyAddress]/index.ts, src/pages/api/config/[site].ts, src/pages/passport/[eoa]/[...ids]/index.astro, yarn.lock
=> the initial implementation: using core-provided-singleton redis

src/fixtures/api/passportItem/index.ts
=> Apply new API to connect to Redis to /og/image/*

src/pages/passport/[eoa]/[...ids]/index.astro
Adjusted the styles to include `justify-self-stretch` and `aspect-square` for improved alignment and proportional scaling of the avatar container. This ensures a better and more consistent appearance across different screen sizes.
=> Update avatar container styles for consistent layout

package.json, src/pages/passport/[eoa]/[...ids]/index.astro, src/pages/passport/components/Modal.vue, src/pages/passport/components/PassportClips.vue, yarn.lock
=> PassportClips opens the initial item when given the `initialSelectedItem` option.

src/components/Feed/VirtualScroll.vue
=> Enable scrolling of body

src/components/Profile/Profile.vue, src/fixtures/url/passports.ts, src/pages/og/image/passport/[eoa]/[passportId]/[...item]/components/ItemView.astro, src/pages/og/image/passport/[eoa]/[passportId]/[...item]/index.astro, src/pages/passport/Layout.astro, src/pages/passport/[eoa]/[...ids]/index.astro, src/pages/passport/components/PassportClip.vue, src/pages/passport/components/PassportClips.vue
Fixed a bug that purchased items were not displayed in the OGP image.
=> Fix ogp for purchased items

package.json, yarn.lock
=> Use @devprotocol/clubs-plugin-awesome-onboarding@0.8.0-beta.2

src/components/Badges/PassportClubName.vue, src/pages/passport/components/PassportClip.vue
=> Tweak the CLUB name badge UI
