- src/components/Perks/Perks.astro
- src/plugins/perks/index.astro
- src/plugins/perks/index.ts
- tenants.ts
Pass perks into tenants.ts instead of using const in individual astro files
> pass perks to tenants

- src/plugins/community/index.astro
- src/plugins/community/index.ts
- src/plugins/quests/index.astro
- src/plugins/quests/index.ts
Community and Quests were not passing props to Sidebar, which was causing the server to break
> adds missing props in sidebar breaking server

- src/fixtures/utility.ts
- src/pages/sites_/[site]/message/sendMessage.ts
- src/plugins/message/components/MessageForm.vue
Add membership check on the server side for NFT gateway contact form. The validation makes sure that the address being validated is the same as the one signing the message. After this validation is in place, we make sure that the address has the required membership, since any user can fake a signing message and directly make api request to the server to contact. Thus this check is necessary at the server to prevent the same.
> feat: add NFT gateway contact form server side membership check

- src/components/GetStarted/GetStarted.vue
When we go to the next step from the get started page, it opens a poup rather than redirecting to niwa.
> feat: add popup from next button on get started page

- src/components/AlmostThere/AlmostThere.vue
- src/constants/plugins.ts
- src/layouts/Landing.astro
- src/pages/almost-there.astro
- src/pages/setConfig.ts
Add in almost there page of the welcome flow. Here we ask the user for dao name and setup the db for that dao with empty/default values.
Notes (**optional**): In this section, while saving the dao using a post request, we need to somehow validate that it's coming from the frontend (that also from a user), otherwise the post request maybe vulnerable to ingestion(invalid data) or ddos attacks. I've commented the part where we can validate that as it requires wallet to be connected, but that can be added in after a discussion.
> feat: almost there section of the welcome flow

- src/layouts/Default.astro
Add a flag variable for detecting draft process.
With this change, `src/layouts/Default.astro` can detect the user's status of drafting process by using `draftOptions` or `isDraft`.
> Add draft flag

- src/pages/api/updateDraftConfig.ts
The api added takes in option params like sig, hash and jwtTokenid(form firebase sdk). If both are not specified the api returns error. but if one or all are specified it validates them respectively and then sets the config accordingly.
Notes (**optional**): The JWT validation code is in place but commented for now since we need to do some signup setup and firebase setup to get those into place which is already worked upon as we speak.
> feat: basic api for draft authentication

- src/components/PreviewBanner/PreviewBanner.svelte
- src/components/ProfileSetupForm/ProfileSetupForm.svelte
- src/components/Sidebar/Sidebar.vue
- src/components/WelcomeConnect/WelcomeConnect.svelte
- src/layouts/Default.astro
- src/pages/authenticating.astro
When in draft mode, the Default layout shows a "Preview Mode" banner
> adds "preview" banner when in draft mode

- astro.config.mjs
- package.json
- scripts/populate.mjs
- src/pages/sites_/[site]/[...page].astro
- src/pages/sites_/[site]/admin/[...page].astro
- src/plugins/default-theme/index.ts
- src/plugins/home/index.ts
- yarn.lock
- clubs-core v0.13.0 has been released with support for theme plugins in addition to standard plugins.
- The first theme plugin is implemented in src/plugins/default-theme.
- Theme plugins have new interfaces `getLayout`, and `meta.theme`.
- After clubs-core v0.13.0, standard plugins can also export layouts. If the item returned by `getPagePaths` has `layout`, the layout file will take precedence over the theme plugin.
> Supports dynamic layout and theme

- src/pages/authentication/[siteName].astro
Add in the missing encode() from clubs-core on configuration when using authentication using firebase.
> fix(integration): encode clubs config when using firebase authenticate

- src/components/PublishConnect/PublishConnect.vue
- src/components/PublishNetworkSelection/PublishNetworkSelection.vue
- src/plugins/memberships/utils/simpleCollections.ts
- Setting Ethers Provider to `Vue.data.provider` will break the Provider because Vue will change the Provider object. Use `let provider: undefined | BaseProvider` where in outside Vue.
- Removed the `@fixtures/wallet` dependency from PublishNetworkSelection.vue because PublishConnect.vue is manipulating `@devprotocol/clubs-core/connection`.
> Bug fixes for Publish page

- src/components/Sidebar/Sidebar.vue
- src/fixtures/dev-kit/index.ts
Dynamically fetches property symbol in sidebar
> fetches property symbol

- src/components/WelcomeConnect/WelcomeConnect.svelte
The change adds showing users feedback on using wallet connection in the connect/ page in the onboarding flow. The feedback shows successful connection, creation and also shows failed in cased any step fails.
> feat(integration): show feedback on connect with wallet in /connect/

- src/pages/[site]/setup/design.astro
- src/pages/[site]/setup/memberships.astro
- src/pages/[site]/setup/preview.astro
- src/pages/[site]/setup/publish.astro
Add next button, that redirects to the next setup step in major setup stages.
> feat(integration): add next button in the setup flow core pages

- src/components/PublishNetworkSelection/PublishNetworkSelection.vue
- src/layouts/BaseClubs.astro
- src/pages/404.astro
Fix discord auth bug in niwa. Update the check for listenAddress to now consider both subdomain(network) as well as the base domain for validity. 
I also had to create a seperate base layout to be used in 404 page- this is because, using the landing layout caused 2 layouts with onSubmitConfig in the setup pages. Hence because of this 2 request for wallet signature confirmations were being made where one resulted in error and caused bad ux.
> fix(bugs): discord auth & double submit config interaction.

- src/fixtures/config.ts
- src/pages/api/addDaoToDraft.ts
- src/pages/api/fetchClubs.ts
- src/pages/api/updateConfig.ts
- src/pages/api/updateDraftConfig.ts
- src/pages/api/verifySiteName/[...site].ts
- src/pages/sites_/[site]/message/sendMessage.ts
This change adds a reconnect startegy and a keep alive startegy while creating redis client instances. This is set to a small number 1 (1 miliseconds). This will enable to keep alive or reconnect the client to the server in case the clients get disconnected unintentionally.
> fix(server): add reconnect startegy and keep alive strategy on redis client

- package.json
- yarn.lock
With using @devprotocol/clubs-core@0.26.0, getPathPaths/getAdminPaths are can use the 3rd params `{getPluginConfigById: (id: string) => ClubsPlugin}`
And each plugin can be defined a new optional meta `id?: string`, and if it is defined, its plugin config will be referable from `getPluginConfigById`.
> Install @devprotocol/clubs-core@0.26.0

- src/components/EmailConnect/EmailConnect.svelte
- src/pages/authentication/[siteName].astro
- src/pages/authentication/index.astro
The backend method to create a link was changed. This broke the updated frontend way we authenticate with Firebase. Reverts to the older way, which works with the updated backend code.
> reverts auth after changing backend

- src/pages/sites_/[site]/[...page].astro
- `getCurrentConfig` increases the number of potential DB connections and increases the waiting time.
- In server builds we can use predefined variables in the `getStaticPath` factory (in static builds, `getStaticPath` uses a limited scope), so precomputing `getCurrentConfig` eliminates the extra awaiting.
> reduce `await`

- src/plugins/quests/components/AdminQuestsForm.vue
This change adds in a fallback value (which is taken from config itself) and the main value is computed using input event value in the quests admin plugins.
> fix(integration): add value from event in quests admin page

- package.json
- src/pages/api/decrypt.ts
- src/pages/api/encrypt.ts
- src/pages/sites_/[site]/message/sendMessage.ts
- yarn.lock
uses jsonwebtoken-esm instead of jsonwebtoken due to breaking vite error
> uses jsonwebtoken-esm

- src/components/AdminPlugins/AdminPlugins.jsx
- src/plugins/admin/plugins.astro
This change attempts to fix the default plugin enable status on the 'admin/plugins' page and also hides the 'admin' plugin to disallow users from disabling it. The 'admin' plugin is removed from the list of plugins before displaying it and then added back in while updating config in the db to achieve preventing users to disable admin plugin.
Notes (**optional**): Another approach to hide the 'admin' plugin could be to keep it in the array and just use css to hide that input field.
> fix: default plugin enable status on admin/plugins

- package.json
- src/pages/api/decrypt.ts
- src/pages/api/encrypt.ts
- src/pages/sites_/[site]/message/sendMessage.ts
- yarn.lock
Revert the code to using `use jsonwebtoken instead of jsonwebtoken-esm` for encrypting and decrypting data.
> fix: /api/encrypt api failure

- src/plugins/default-theme/pages/index.astro
- Supports PageContentHomeBeforeContent slots in the default theme
> Supports PageContentHomeBeforeContent slots in the default theme

- src/components/Domain/Domain.vue
- src/pages/domain.astro
Allows presetting of domain name via a URL query `name`.
> Support domain preset name with query param

- src/constants/plugins.ts
- src/pages/api/plugins/addPluginToClub.ts
To install "Posts" plugin, `InstallablePlugins.pluginOptions` requires a dynamic method and so now supports functional types as a new union type.
> Supports a new type of InstallablePlugins.pluginOptions as a function

- src/fixtures/flags/index.ts
- src/plugins/marketplace/admin.astro
- Add `@fixtures/flags` APIs
- Initially, the visibility of Stores plugin on the marketplace is controlled by the `flag:stores-on-marketplace` flag.
> Implement feature flags

- src/components/PublishNetworkSelection/PublishNetworkSelection.vue
- src/pages/[site]/setup/publish.astro
Removes check for allowAccess when publishing. This was allowing selected users to publish in the Niwa popup. The check has been now removed from Niwa, and is no longer necessary in Clubs.
> removes allowAccess check when publishing

- src/constants/plugins.ts
- src/pages/api/plugins/addPluginToClub.ts
By defining `InstallablePlugins.navigationLinks`, navigation links can be added automatically when installing a plugin.
> Add new options for InstallablePlugins: navigationLinks

- .prettierrc.json
removes prettier-plugin-tailwindcss, which was causing prettier to crash on file save
> removes prettier-plugin-tailwindcss

- src/plugins/collections/checkout.astro
- src/plugins/collections/index.ts
As the title said.
Potential improvement candidates:
- Checkout.astro in clubs-core can use `Props` type declaration to provide better type to parent components.
- Checkout.astro in clubs-core basically uses the same named parameters as Checkout.vue, but replaces only `destination` with `propertyAddress`. This can be changed to use the same parameters as in Checkout.vue. 
> Fix issue on props passing

- src/components/AdminMembershipsForm/MembershipOption.svelte
Remove prefetch from svelte to load the newly uploaded image to IMGUR immediately.
> fix: remove prefetch from MembershipOption

- src/components/Domain/Domain.vue
Maybe, we can write the same process in more natural way with composition API:
```js
const i18n = ref<ReturnType<typeof i18nBase>>()
onMounted(() => {
i18n.value = i18nBase(navigator.languages)
})
```
> fix a bug that i18n parts on Domain page does not update even after mounted

- src/pages/sites_/[site]/[...page].astro
- src/pages/sites_/[site]/admin/[...page].astro
The regexp paths are already available in the API routes. But pages/admins ware not. This change allow pages/admins to enable regexp-paths-dependent routes.
With this change, some regexp-paths-dependent pages like https://github.com/dev-protocol/clubs-plugin-posts/pull/786 will be available on clubsx.
> Enable regexp-paths-dependent route for pages/admins

- src/pages/api/hasCreationLimitReached/[...identifier].ts
- src/pages/api/profile/[id].ts
`/api/profile/[id]` and `/api/hasCreationLimitReached/[id]` returns cors headers now.
> `/api/profile/[id]` and `/api/hasCreationLimitReached/[id]` APIs are now returning cors header

- src/plugins/default-theme/pages/index.astro
The display slots for PageContentHomeBeforeContent have been moved to the top of the 'grid gap-6' article within the default-theme index page. This change ensures the correct order of content rendering according to the sectionsOrderConfig setting.
> Reorder display slots in default-theme index page

- src/plugins/achievements/handlers/addAchievement.ts
- src/plugins/achievements/utils.ts
Modify the API to input a parameter `noOfCopies` which signifies the number of achievements to issue. Then create `noOfCopies` achievements (as apposed to creating 1 achievement only) and return the created achievements in the array format.
This change will allow us to assign multiple (>=1) achievements for a single record in airtable or api call.
Notes: **The achievements created will all have the exactly same data.**
> feat: add logic to issue >=1 achievements in a single API call

- scripts/redis-info.mjs
clears up ocassional error when redis has already quit
> clears up ocassional error when redis has already quit

- src/components/AdminMembershipsForm/AdminMembershipsAdditionForm.svelte
- src/components/AdminMembershipsForm/i18n/index.ts
- src/components/Collections/CreateCollections.svelte
- src/constants/memberships.ts
- Modify the instant payment type to 1 (100%) and change limit of maxCustomFee100 to 100.
> feat: make default staking 0% and custom field max to 100

- src/plugins/clubs-payments/utils/compose-items.ts
- src/plugins/collections/index.ts
- src/plugins/memberships/index.ts
- In compose items add support for shops plugin elements. The compose items function find the membership with the matching payload in shops plugin and returns the entire collection even if one membership of that collection matches the payload.
> feat: shops plugin payment plugin support.

- .github/workflows/build.yml
- .github/workflows/deploy-preview.yml
- .github/workflows/deploy.yml
- README.md
Updated the deployment pipeline conditions to ensure that any changes to the `main` branch are automatically deployed as a prerelease.
Meanwhile, deployments to the live environment will still require the creation of a release.
This adjustment simplifies the management of semantic versioning by removing the necessity for npm version updates for prereleases.
> Any changes in main always triggers prerelease deployment

- src/fixtures/api/assets/redis.ts
- src/plugins/achievements/db/schema.ts
- **Achievements** - Using `$.KEY[*].KEY` expression, fixed the bug does not index numberAttributes/stringAttributes.
- **Assets** - Fixed `doc::clubs:asset` and `doc::clubs:asset:log` prefixes partially overlap.
> Fix some indexes

- src/fixtures/api/json.ts
- src/pages/api/profile/index.ts
`Profile` type has new option values ​​to support Passport Skins.
For now, Profiles are still stored as static strings and are not indexed.
> Profile supports Passport Skins

- src/fixtures/api/assets/schema.ts
- src/fixtures/api/assets/utils.ts
- src/pages/api/cron/assets.ts
Add an assetFetcherType which fetches and confirms the type of smart-contract used. If it's a sToken we then fetch payload in the passport-item redis schemas. If the payload is found there we conclude it's a passport-item.
> feat: filter all sTokens into 'nft' (membership) and 'passport-item'

- src/pages/api/profile/index.ts
- src/pages/api/profile/updateLike.ts
- src/pages/passport/[eoa]/[...ids]/index.astro
- src/pages/passport/components/UserProfileEdit.svelte
- src/pages/passport/i18n/index.ts
@aggre  This PR:
- Adds id and name to profile.skins[0].
- The passport skin name is an input field.
- The passport skin id is nanoid generated only when it is not present (meaning it's generated only once).
- Adds routing based on skin.id.
- if id is not present will return basic user page (with name, description, sns, clubs and achievements). will not show passport items.
> feat: update passport feature for name, and id and add nanoid routing

- src/pages/passport/[eoa]/[...ids]/index.astro
- src/pages/passport/components/PassportClip.vue
- src/pages/passport/components/PassportClips.vue
> Feat: Share Item

- src/pages/api/profile/updateLike.ts
- src/pages/passport/components/Like.svelte
Thanks @aggre for suggestion of using setTimeout. I have used
```js
clearTimeout(timeoutId)
timeoutId = setTimeout(async () => {
if (pendingLikes === 0) return clearInterval(intervalId)
await submitLikes()
}, 1000)
```
So, this pushes the latest pending like state called via submitLikes function just after the user stops clicking. 
> Update: Infinite Like logic to accommodate large like count instantly

- src/pages/api/profile/index.ts
- src/pages/api/profile/updateLike.ts
- src/pages/passport/[eoa]/[...ids]/index.astro
- src/pages/passport/components/Like.svelte
- src/pages/passport/i18n/index.ts
This PR adds support for likes on multiple skins on a passport profile. This PR also adds a default likes to the profile which doesn't represent any skin but the profile itself.
> Feat multiple skins like

- src/pages/api/profile/[id]/index.ts
- src/pages/passport/components/UserProfileEdit.svelte
Add optional caching in the getProfile API. This is to help the passport edit page get the updated profile in all the API calls.
> perf: add optional caching in getProfile to help edit page get updated results

- src/pages/clubs/index.astro
- src/pages/index.astro
- src/pages/passport/[eoa]/[...ids]/index.astro
- src/pages/passport/[id]/edit.astro
- src/pages/passport/components/EditPagePurchasedClips.svelte
- src/pages/passport/components/Onboarding.vue
- src/pages/passport/i18n/index.ts
- src/pages/signin.astro
- Bug where UGC cannot be added when there are no purchased items.
- Trivial improvement of UI of passport onboarding screen.
> Some Bug fix for Passports

- src/pages/passport/components/EditPassportSkinShowcase.svelte
- src/pages/passport/components/PassportClips.vue
> `test` - when the screen size is narrow, the clips section will be 2 columns.
